spring:
  profiles:
    active: local

  # 로컬, 개발, 운영 환경의 공통된 설정

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secretKey: ${JWT_SECRET}
  access:
    expiration: 1800000
  refresh:
    expiration: 259200000

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack.auto: false
    region: ${AWS_REGION:ap-northeast-2}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

springdoc:
  show-login-endpoint: true

server:
  servlet:
    session:
      cookie:
        same-site: none

aes:
  secret:
    key: ${AES_SECRET_KEY}
    salt: ${AES_SECRET_SALT}

# 출석 위치 검증 정확도 (위경도 오차 제곱, 기본값: 0.0001)
attendance:
  location:
    accuracy: ${ATTENDANCE_LOCATION_ACCURACY:0.001}

# Actuator 설정
management:
  health:
    mail:
      enabled: false
