# prod - server

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: ${PROD_DDL_AUTO:none}
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_DB_PATH}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PWD}

  config:
    import: classpath:variable/variable-prod.yml

springdoc:
  swagger-ui:
    enabled: false
